#+TITLE: LibreServer
#+AUTHOR: Bob Mottram
#+EMAIL: bob@libreserver.org
#+KEYWORDS: libreserver, installation, self-hosting
#+DESCRIPTION: LibreServer installation
#+OPTIONS: ^:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="libreserver.css" />

* Installation

** 1. Download
[[https://libreserver.org/downloads][Download the disk image]] for your server architecture.

** 2. Copy to drive
In a terminal, copy the image to your drive. This could be microSD, a USB stick or an SSD.

#+BEGIN_SRC bash
xzcat libreserver-bullseye-*-amd64.img.xz | \
  sudo dd bs=4M of=/dev/sdX conv=fsync status=progress
#+END_SRC

Where *sdX* is the name of your drive.

** 3. Plug in
Connect everything up.

 * Ethernet cable between your internet router and your server.
 * Plug in the drive.
 * Connect power supply.

If your server fails to boot then go back to step 2 and try writing to the drive again, or using a different drive. Sometimes copying the image to the drive is not always entirely reliable.

** 4. Locate on the network
Find you server's local IP address. It will usually start with 192.168.. A typical way to do this is to log in to your internet router and show the list of devices on your local network.

** 5. Log in
Log into your server using ssh.

#+BEGIN_SRC bash
ssh admin@192.168.x.y
#+END_SRC

The initial password is **libreserver**. On first login you will be asked to change this and the server will log you out again. Log back in with your chosen password. Note that /the password that you entered is temporary/ and will be thrown away when installation is complete.

** 6. Start the install
Follow the instructions to begin the install. Typically this will be:

#+BEGIN_SRC bash
sudo libreserver menuconfig
#+END_SRC

or for the onion version:

#+BEGIN_SRC bash
sudo libreserver menuconfig-onion
#+END_SRC

You will be prompted to select a language and then be given a new password. Write this down or store it in a password manager.

If you are not installing the onion version then you will be also be asked for dynamic DNS and domain name. The domain name must be one which you own, and not a /free-as-in-gratis/ subdomain.

Installation may take a long time - possibly up to a few hours - depending on your type of drive and internet bandwidth, but you can leave it running unattended. microSD cards and USB sticks are typically quite slow (unless it's USB3 and your hardware has USB3 sockets).

** 7. Browse to admin
When installation is complete you can log into your server with a browser.

#+BEGIN_SRC bash
http://192.168.x.y/admin
#+END_SRC

The username is **admin** and the password is the one you wrote down previously.
