#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# login functions
#
# License
# =======
#
# Copyright (C) 2014-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function change_login_message {
    if [[ $(is_completed "${FUNCNAME[0]}") == "1" ]]; then
        return
    fi

    # remove automatic motd creator if it exists
    if [ -f /etc/init.d/motd ]; then
        rm -f /etc/init.d/motd
    fi

    { echo '    _____               _           _';
      echo '   |   __|___ ___ ___ _| |___ _____| |_ ___ ___ ___';
      echo '   |   __|  _| -_| -_| . | . |     | . | . |   | -_|';
      echo '   |__|  |_| |___|___|___|___|_|_|_|___|___|_|_|___|';
      echo '';
      echo $'          Your Data.  Your Server.  Your Place.';
      echo ''; } > /etc/motd

    mark_completed "${FUNCNAME[0]}"
}

# NOTE: deliberately no exit 0
