#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Removes an email address rule from the email configuration
#
# License
# =======
#
# Copyright (C) 2015-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='libreserver'

export TEXTDOMAIN=${PROJECT_NAME}-rmemail
export TEXTDOMAINDIR="/usr/share/locale"

MYUSERNAME=$USER

function show_help {
    echo ''
    echo $"${PROJECT_NAME}-rmemail -u [username] -e [email address]"
    echo ''
    exit 0
}

while [ $# -gt 1 ]
do
key="$1"

case $key in
    -h|--help)
    show_help
    ;;
    -u|--user)
    shift
    MYUSERNAME="$1"
    ;;
    -e|--email)
    shift
    EMAILADDRESS="$1"
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

if ! [[ $MYUSERNAME && $EMAILADDRESS ]]; then
    show_help
fi

MUTTRC="/home/$MYUSERNAME/.muttrc"
PM=/home/$MYUSERNAME/.procmailrc

if grep -q "Email rule for $EMAILADDRESS ->" "$PM"; then
    sed -i "/# Email rule for $EMAILADDRESS ->.*/,/# End of rule/d" "$PM"
fi

exit 0
