#!/bin/bash
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# Show help
#
# License
# =======
#
# Copyright (C) 2014-2023 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function show_help {
    echo ''
    echo $"${PROJECT_NAME} -c [configuration file]"
    echo ''
    echo $'  -h --help             Show help'
    echo $'     menuconfig         Easy interactive installation'
    echo $'     menuconfig-full    Full interactive installation'
    echo $'     menuconfig-onion   Interactive installation for onion-only sites'
    echo $'  -c --config           Installing from a configuration file'
    echo $'     --bbb              Installing on Beaglebone Black'
    echo $'  -u --user             User to install the system as'
    echo $'  -d --domain           Default domain name'
    echo $'  -s --system           System type'
    echo $'     --ip               Static LAN IP address of the system'
    echo $'     --iprouter         LAN IP address of the internet router'
    echo $'     --ddns             Dynamic DNS provider domain'
    echo $'     --ddnsuser         Dynamic DNS provider username'
    echo $'     --ddnspass         Dynamic DNS provider password'
    echo ''
    echo $'     --ssh              ssh port number'
    echo $'     --cores            Number of CPU cores'
    echo $'     --name             Your name'
    echo $'     --email            Your email address'
    echo $'     --usb              Path for the USB drive (eg. /dev/sdb1)'
    echo $'     --vpass            Mumble server password'
    echo $'     --vport            Mumble server port'
    echo $'     --ns1              First DNS nameserver'
    echo $'     --ns2              Second DNS nameserver'
    echo $'     --repo             Debian repository'
    echo ''
    exit 0
}

# NOTE: deliberately no exit 0
