#!/usr/bin/env python3
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# Script to copy epicyon markdown blogs to the bludit site
#
# License
# =======
#
# Copyright (C) 2025 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import argparse
import uuid
import hashlib
import json
from shutil import copyfile
from collections import OrderedDict


def _copy_files_to_blog(markdown_dir: str, blog_dir: str,
                        username: str) -> None:
    """Save markdown files to bludit database
    """
    pages_dict = {}

    # get the dictionary filename
    databases_dir = blog_dir + '/bl-content/databases'
    if not os.path.isdir(databases_dir):
        try:
            os.mkdir(databases_dir)
        except OSError:
            return
    pages_dict_filename = databases_dir + '/pages.php'

    # load the dictionary
    if os.path.isfile(pages_dict_filename):
        pages_dict_str = ''
        with open(pages_dict_filename, 'r', encoding='utf8') as fp_database:
            pages_dict_str = fp_database.read()
            pages_dict_str = pages_dict_str.split('>', 1)[1]
        try:
            pages_dict2 = json.loads(pages_dict_str)
            pages_dict = pages_dict2
        except BaseException:
            return

    for _, _, files in os.walk(markdown_dir):
        for mkdown_file in files:
            if not mkdown_file.endswith('.md'):
                continue
            filename = os.path.join(markdown_dir, mkdown_file)
            if not os.path.isfile(filename):
                continue
            # create a pages directory
            blog_subdir = mkdown_file.replace('.md', '').replace(' ', '_')
            blog_date = blog_subdir.split('_')[0]
            blog_pages_dir = blog_dir + '/bl-content/pages/' + blog_subdir
            if not os.path.isdir(blog_pages_dir):
                try:
                    os.mkdir(blog_pages_dir)
                except OSError:
                    continue
            # save index.txt to the pages directory
            try:
                copyfile(filename, blog_pages_dir + '/index.txt')
            except OSError:
                continue

            # update the dictionary
            md5_str = hashlib.md5(open(filename, 'rb').read()).hexdigest()
            pages_dict[blog_subdir] = {
                "title": "",
                "description": "",
                "username": username,
                "tags": [],
                "type": "published",
                "date": blog_date,
                "dateModified": "",
                "position": 0,
                "coverImage": "",
                "category": "",
                "md5file": md5_str,
                "uuid": str(uuid.uuid4()),
                "allowComments": True,
                "template": "",
                "noindex": False,
                "nofollow": False,
                "noarchive": False,
                "custom": [
                    False
                ]
            }
        break

    # latest blog post should appear at the top
    pages_dict_descending = \
        OrderedDict(sorted(pages_dict.items(),
                           key=lambda kv: kv[1]['date'],
                           reverse=True))

    # add prefix
    prefix = "<?php defined('BLUDIT') or die('Bludit CMS.'); ?>\n"
    try:
        with open(pages_dict_filename, 'w+', encoding='utf8') as fp_database:
            fp_database.write(prefix)
    except OSError:
        pass
    # save the dictionary
    try:
        with open(pages_dict_filename, 'a', encoding='utf8') as fp_database:
            fp_database.write(json.dumps(pages_dict_descending))
    except OSError:
        pass


def _copy_markdown_to_blog(epicyon_accounts_dir: str,
                           blog_dir: str) -> None:
    """Copy epicyon blog markdown files to bludit
    """
    for _, dirs, _ in os.walk(epicyon_accounts_dir):
        for account_dir in dirs:
            if '@' not in account_dir:
                continue
            if 'inbox@' in account_dir or 'news@' in account_dir:
                continue
            acct_dir = os.path.join(epicyon_accounts_dir, account_dir)
            markdown_dir = acct_dir + '/markdown'
            if not os.path.isdir(markdown_dir):
                continue
            username = account_dir.split('@')[0]
            _copy_files_to_blog(markdown_dir, blog_dir, username)
        break


PARSER = \
    argparse.ArgumentParser(description='Epicyon blog to Bludit converter')
PARSER.add_argument('-b', '--blogdomain', dest='blogdomain', type=str,
                    default=None,
                    help='The domain on which bludit is installed')

args = PARSER.parse_args()

if not args.blogdomain:
    print('Please specify a domain on which bludit is installed with ' +
          '--blogdomain [domain]')
    sys.exit()

BLUDIT_DIR = '/var/www/' + args.blogdomain + '/htdocs'
if not os.path.isdir(BLUDIT_DIR + '/bl-content/pages'):
    print('Missing directory: ' + BLUDIT_DIR + '/bl-content/pages')
    sys.exit()

EPICYON_ACCOUNTS_DIR = '/etc/epicyon/accounts'
_copy_markdown_to_blog(EPICYON_ACCOUNTS_DIR, BLUDIT_DIR)
