#!/bin/bash
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# Command to upgrade the system
#
# License
# =======
#
# Copyright (C) 2015-2025 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='libreserver'

PROJECT_DIR="$HOME/${PROJECT_NAME}"

# An optional configuration file which overrides some of these variables
CONFIGURATION_FILE="$HOME/${PROJECT_NAME}.cfg"

DEFAULT_PROJECT_REPO="https://gitlab.com/bashrc2/${PROJECT_NAME}"
PROJECT_REPO=$DEFAULT_PROJECT_REPO

# file used to store the number of ssh connections and warn if the count gets high
ssh_sessions_count_filename=/root/.ssh_sessions_count

CURRENT_BRANCH=trixie

UPGRADE_PARAM="$1"

# Is letsencrypt updating its certificates?
# If yes then skip the upgrade to avoid any collisions
if [ -f ~/temp_renewletsencrypt.txt ]; then
    if [ -f /tmp/.upgrading ]; then
        rm /tmp/.upgrading
    fi
    exit 0
fi

# don't do updates if the setup process has not happened
if [ -f /root/.install_state.txt ]; then
    curr_install_state=$(cat /root/.install_state.txt)
    if [ "$curr_install_state" ]; then
        # shellcheck disable=SC2086
        if [ $curr_install_state -ne 4 ]; then
            exit 0
        fi
    fi
fi

source /usr/local/bin/${PROJECT_NAME}-shortcuts

UTILS_FILES="/usr/share/${PROJECT_NAME}/utils/${PROJECT_NAME}-utils-*"
for f in $UTILS_FILES
do
    source "$f"
done

source "/usr/share/${PROJECT_NAME}/base/${PROJECT_NAME}-base-email"
source "/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-xmpp"

rename_config_param "LOCAL_NETWORK_STATIC_IP_ADDRESS" "LOCAL_NETWORK_STATIC_IPv4_ADDRESS"
rename_config_param "ROUTER_IP_ADDRESS" "ROUTER_IPv4_ADDRESS"

# allow icmp for ipv6
if grep -q 'drop icmp ipv6' /etc/nftables.conf; then
    sed -i '/drop icmp ipv6/d' /etc/nftables.conf
    reload_firewall
fi

# remove static interfaces settings if dynamic exists
if [ -f /etc/network/interfaces.d/dynamic ]; then
    if [ -f /etc/network/interfaces.d/static ]; then
        rm /etc/network/interfaces.d/static
    fi
fi

read_config_param PROJECT_REPO
if [[ "$PROJECT_REPO" == *"github.com/bashrc2/${PROJECT_NAME}" || "$PROJECT_REPO" == *"libreserver.org"* ]]; then
    PROJECT_REPO=$DEFAULT_PROJECT_REPO
    write_config_param PROJECT_REPO "$PROJECT_REPO"
fi
if [[ "$PROJECT_REPO" == 'none' ]]; then
    if [ -f /tmp/.upgrading ]; then
        rm /tmp/.upgrading
    fi
    exit 0
fi

read_config_param ONION_ONLY
read_config_param DEFAULT_DOMAIN_NAME

read_config_param STABLE_BRANCH
if [ "$STABLE_BRANCH" ]; then
    if [ ${#STABLE_BRANCH} -gt 0 ]; then
        CURRENT_BRANCH="$STABLE_BRANCH"
    fi
fi

read_config_param DEVELOPMENT_BRANCH
if [ "$DEVELOPMENT_BRANCH" ]; then
    if [ ${#DEVELOPMENT_BRANCH} -gt 0 ]; then
        CURRENT_BRANCH="$DEVELOPMENT_BRANCH"
    fi
fi

UPGRADE_LOG=/var/log/libreserver_upgrade.log
echo "Upgrade $(date)" > ${UPGRADE_LOG}

# upgrading file prevents USB canary or other jobs from activating
rm -rf /tmp/*
echo "Set upgrading flag" >> ${UPGRADE_LOG}
touch /tmp/.upgrading

if [ -f /usr/bin/backupdatabases ]; then
    if grep -q "cat /root/dbpass" /usr/bin/backupdatabases; then
        # update to using the password manager
        echo "Backup databases" >> ${UPGRADE_LOG}
        sed -i "s|cat /root/dbpass|${PROJECT_NAME}-pass -u root -a mariadb|g" /usr/bin/backupdatabases
    fi
fi

#update-ca-certificates

if [ ! -d "$PROJECT_DIR" ]; then
    git_clone "$PROJECT_REPO" "$PROJECT_DIR"
fi

if [ -d "$PROJECT_DIR" ]; then
    if [ -f "$CONFIGURATION_FILE" ]; then
        case "$UPGRADE_PARAM" in
            "change_domain")
                change_default_domain_name
                ;;
            *)
                echo "PROJECT_DIR ${PROJECT_DIR}" >> ${UPGRADE_LOG}
                cd "${PROJECT_DIR}" || exit 24
                git config pull.rebase false
                if [[ "$CURRENT_BRANCH" == *'master' ]]; then
                    git_pull ${PROJECT_REPO}
                else
                    git_pull ${PROJECT_REPO} "origin/${CURRENT_BRANCH}"
                fi
                git checkout "${CURRENT_BRANCH}"
                git pull
                make install
                echo "Installed" >> ${UPGRADE_LOG}
                if [ -d /usr/share/${PROJECT_NAME} ]; then
                    chown -R root:root /usr/share/${PROJECT_NAME}
                    chmod -R +r /usr/share/${PROJECT_NAME}
                    echo "Set permissions" >> ${UPGRADE_LOG}
                fi

                if ! ${PROJECT_NAME} -c "$CONFIGURATION_FILE"; then
                    if [ -f /tmp/.upgrading ]; then
                        rm /tmp/.upgrading
                    fi
                    echo "Upgrade failed" >> ${UPGRADE_LOG}
                    /bin/bash /usr/local/bin/${PROJECT_NAME}-notification -s "LibreServer upgrade" -m "Upgrade failed"
                    exit 45
                fi

                echo "journalctl vacuum" >> ${UPGRADE_LOG}
                journalctl --vacuum-size=200M
                echo "update port scan defense" >> ${UPGRADE_LOG}
                update_portscan_defense
                echo "install dynamic dns" >> ${UPGRADE_LOG}
                install_dynamicdns
                echo "migrate torrc" >> ${UPGRADE_LOG}
                torrc_migrate
                echo "email remove frozen" >> ${UPGRADE_LOG}
                email_remove_frozen
                echo "exim enable tls" >> ${UPGRADE_LOG}
                exim_enable_tls
                echo "add xmpp onion to email" >> ${UPGRADE_LOG}
                add_xmpp_onion_to_email
                echo "add xmpp onion to http upload" >> ${UPGRADE_LOG}
                add_xmpp_onion_http_upload
                echo "configure dkim" >> ${UPGRADE_LOG}
                configure_dkim
                echo "email add xmpp headers" >> ${UPGRADE_LOG}
                email_add_xmpp_headers
                echo "email update riseup" >> ${UPGRADE_LOG}
                email_update_riseup_onion_domain
                echo "upgrade nodejs" >> ${UPGRADE_LOG}
                upgrade_nodejs
                # if [[ "$ONION_ONLY" == 'no' ]]; then
                    # echo "Reinstalling python packages" >> ${UPGRADE_LOG}
                    # REINSTALL_PACKAGES python3-pkg-resources python3-setuptools python3-openssl python3-cryptography
                    # echo "Install certbot" >> ${UPGRADE_LOG}
                    # INSTALL_PACKAGES certbot
                # fi
                echo "Email install tls" >> ${UPGRADE_LOG}
                email_install_tls
                echo "Email disable chunking" >> ${UPGRADE_LOG}
                email_disable_chunking
                echo "Remove IP addresses from email logs" >> ${UPGRADE_LOG}
                remove_ip_addresses_from_email_logs
                echo "Remove exim backups" >> ${UPGRADE_LOG}
                rm /etc/exim4/exim4.conf.template.bak*
                echo "Email upgrade onion domain" >> ${UPGRADE_LOG}
                email_update_onion_domain
                echo "Prevent mail process overrun" >> ${UPGRADE_LOG}
                prevent_mail_process_overrun
                echo "Android update apps" >> ${UPGRADE_LOG}
                android_update_apps nowebadmin
                echo "Populate keyservers" >> ${UPGRADE_LOG}
                populate_keyservers
                echo "Disable email encryption at rest" >> ${UPGRADE_LOG}
                disable_email_encryption_at_rest
                echo "Email remove html" >> ${UPGRADE_LOG}
                email_remove_html
                echo "Email flooding defense" >> ${UPGRADE_LOG}
                email_flooding_defense
                echo "Email repair saslauthd" >> ${UPGRADE_LOG}
                email_repair_saslauthd
                echo "Email configure i2p" >> ${UPGRADE_LOG}
                configure_email_i2p
                if [ -f /var/log/freedns_@_update.log ]; then
                    echo "Remove freedns log" >> ${UPGRADE_LOG}
                    rm /var/log/freedns_@_update.log
                fi
                echo "Upgrade iptables" >> ${UPGRADE_LOG}
                upgrade_iptables
                echo "Update email onion dns" >> ${UPGRADE_LOG}
                update_email_onion_dns
                if [ -d /home/pi ]; then
                    echo "Removing default raspberry pi user account" >> ${UPGRADE_LOG}
                    echo $'Removing default raspberry pi user account'
                    chmod 600 /etc/shadow
                    chmod 600 /etc/gshadow
                    userdel -r pi
                    groupdel pi
                    chmod 0000 /etc/shadow
                    chmod 0000 /etc/gshadow
                fi
                if [ -f ${ssh_sessions_count_filename} ]; then
                    echo "Removing sessions count" >> ${UPGRADE_LOG}
                    rm ${ssh_sessions_count_filename}
                fi
                # enable ipv6 on websites
                echo "enable ipv6 on websites" >> ${UPGRADE_LOG}
                sed -i 's|#listen \[::|listen \[::|g' /etc/nginx/sites-available/*
                echo "Block web crawlers" >> ${UPGRADE_LOG}
                block_web_crawlers
                echo "Restart web server" >> ${UPGRADE_LOG}
                systemctl restart nginx
                #defrag_filesystem
                ;;
        esac
    fi
fi

echo "Restart i2p" >> ${UPGRADE_LOG}
systemctl restart i2pd
echo "Restart web admin" >> ${UPGRADE_LOG}
systemctl restart webadmin

# upgrading file prevents USB canary from activating
if [ -f /tmp/.upgrading ]; then
    echo "Remove upgrading flag" >> ${UPGRADE_LOG}
    rm /tmp/.upgrading
fi

# If logging was left on then turn it off
echo "Turn logging off" >> ${UPGRADE_LOG}
${PROJECT_NAME}-logging off

# if the kernel was upgraded then the options may also need to be changed
ruleset=$(/usr/sbin/nft list ruleset)
if [[ "${ruleset}" != *"portscan"* ]]; then
    if [[ "$(firewall_kernel_options)" == *"1" ]]; then
        echo "Rebooting for kernel options to take effect" >> ${UPGRADE_LOG}
        echo $'Rebooting for kernel options to take effect'
        systemctl reboot -i
    fi
fi
echo "End of upgrade $(date)" >> ${UPGRADE_LOG}

# deliberately there is no 'exit 0' here
