#!/bin/bash
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# etesync server
# https://github.com/victor-rds/docker-etebase/blob/229629f4c5f5c3a3c3517f62f9433d3402749f21/tags/base/Dockerfile
#
# License
# =======
#
# Copyright (C) 2018-2023 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

VARIANTS='full full-vim full-micro'

APP_CATEGORY=sync

IN_DEFAULT_INSTALL=0
INSTALLED_ON_DEFAULT_DOMAIN=0
SHOW_ON_ABOUT=1
REQUIRES_APP=

# whether to show the domain name in the web UI
SHOW_DOMAIN_IN_WEBADMIN=1
NOT_ON_API=0
NOT_ON_HOMEPAGE=1

ETESYNC_DOMAIN_NAME=
ETESYNC_CODE=
ETESYNC_PATH=/etc/etesync
ETESYNC_DATA_PATH=/etesync_data
ETESYNC_ONION_PORT=9860
ETESYNC_I2P_PORT=6568
ETESYNC_REPO="https://github.com/etesync/server-skeleton"
ETESYNC_COMMIT='55d3fb7e8ec10e55725721c7300bb25f8e49eac8'
ETESYNC_PORT_INTERNAL=8292

# These parameters are used by the FreedomBox mobile app and web UI
ETESYNC_SHORT_DESCRIPTION='End-to-end encrypted sync of calendar and contacts between devices'
ETESYNC_DESCRIPTION='Secure, end-to-end encrypted and journaled personal information cloud synchronization for Android and the desktop, supporting contacts and calendars'
ETESYNC_MOBILE_APP_URL='https://f-droid.org/en/packages/com.etesync.syncadapter/'

etesync_variables=(ONION_ONLY
                   ETESYNC_DOMAIN_NAME
                   ETESYNC_CODE
                   DDNS_PROVIDER
                   MY_EMAIL_ADDRESS
                   MY_USERNAME)

function upgrade_distro_etesync {
    target_distro="$1"

    if [[ "$target_distro" == 'bookworm' ]]; then
        echo -n ''
    fi
}

function logging_on_etesync {
    echo -n ''
}

function logging_off_etesync {
    echo -n ''
}

function remove_user_etesync {
    remove_username="$1"

    etesync_temp_filename=/usr/bin/remove-user-etesync
    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); u = User.objects.get(username='$remove_username'); u.delete();\" | python3 manage.py shell";
      echo "\"${PROJECT_NAME}-pass\" -u \"$remove_username\" --rmapp etesync";
      echo 'deactivate'; } > $etesync_temp_filename
    chmod +x $etesync_temp_filename
    /bin/bash $etesync_temp_filename
    rm $etesync_temp_filename
}

function add_user_etesync {
    new_username="$1"
    new_user_password="$2"

    etesync_temp_filename=/usr/bin/add-user-etesync
    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); u = User.objects.create_user('$new_username', '${new_username}@\$(hostname)', '$new_user_password'); u.save();\" | python3 manage.py shell";
      echo "\"${PROJECT_NAME}-pass\" -u \"$new_username\" -a etesync -p \"$new_user_password\"";
      echo 'deactivate'; } > $etesync_temp_filename
    chmod +x $etesync_temp_filename
    /bin/bash $etesync_temp_filename
    echo '0'
}

function install_interactive_etesync {
    if [ ! "$ONION_ONLY" ]; then
        ONION_ONLY='no'
    fi

    if [[ "$ONION_ONLY" != "no" ]]; then
        ETESYNC_DOMAIN_NAME='etesync.local'
        write_config_param "ETESYNC_DOMAIN_NAME" "$ETESYNC_DOMAIN_NAME"
    else
        interactive_site_details "etesync" "ETESYNC_DOMAIN_NAME" "ETESYNC_CODE"
    fi
    APP_INSTALLED=1
}

function change_password_etesync {
    curr_username="$1"
    new_user_password="$2"

    etesync_temp_filename=/usr/bin/change-password-etesync
    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); u = User.objects.get(username='$curr_username'); u.set_password('$new_user_password'); u.save();\" | python3 manage.py shell";
      echo "\"${PROJECT_NAME}-pass\" -u \"$curr_username\" -a etesync -p \"$new_user_password\"";
      echo 'deactivate'; } > $etesync_temp_filename
    chmod +x $etesync_temp_filename
    /bin/bash $etesync_temp_filename
    rm $etesync_temp_filename
}

function reconfigure_etesync {
    # This is used if you need to switch identity. Dump old keys and generate new ones
    echo -n ''
}

function configure_interactive_etesync {
    W=(1 $"Option 1"
       2 $"Option 2")

    while true
    do
        # shellcheck disable=SC2068
        selection=$(dialog --backtitle $"LibreServer Administrator Control Panel" --title $"etesync" --menu $"Choose an operation, or ESC for main menu:" 14 70 3 "${W[@]}" 3>&2 2>&1 1>&3)

        if [ ! "$selection" ]; then
            break
        fi
        case $selection in
            1) # call some function for option 1
            ;;
            2) # call some function for option 2
            ;;
        esac
    done
}

function upgrade_etesync {
    if [ -f /usr/bin/change-password-etesync ]; then
        rm /usr/bin/change-password-etesync
    fi
    CURR_ETESYNC_COMMIT=$(get_completion_param "etesync commit")
    if [[ "$CURR_ETESYNC_COMMIT" == "$ETESYNC_COMMIT" ]]; then
        return
    fi

    if grep -q "etesync domain" "$COMPLETION_FILE"; then
        ETESYNC_DOMAIN_NAME=$(get_completion_param "etesync domain")
    fi

    # update to the next commit
    set_repo_commit "${ETESYNC_PATH}" "etesync commit" "$ETESYNC_COMMIT" "$ETESYNC_REPO"

    etesync_temp_filename=/usr/bin/upgrade-etesync
    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "pip3 install -U -r requirements.txt";
      echo "python3 manage.py migrate";
      echo 'deactivate'; } > $etesync_temp_filename
    chmod +x $etesync_temp_filename
    /bin/bash $etesync_temp_filename

    chown -R etesync:etesync "${ETESYNC_PATH}"
    chown -R www-data:www-data "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
    systemctl restart etesync
}

function backup_local_etesync {
    ETESYNC_DOMAIN_NAME='etesync'
    if grep -q "etesync domain" "$COMPLETION_FILE"; then
        ETESYNC_DOMAIN_NAME=$(get_completion_param "etesync domain")
    fi

    suspend_site "${ETESYNC_DOMAIN_NAME}"

    systemctl stop etesync

    source_directory="${ETESYNC_DATA_PATH}"
    dest_directory=etesyncdata
    backup_directory_to_usb "$source_directory" $dest_directory

    source_directory="${ETESYNC_PATH}"
    dest_directory=etesync
    backup_directory_to_usb "$source_directory" $dest_directory

    source_directory="/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
    dest_directory=etesyncstatic
    backup_directory_to_usb "$source_directory" $dest_directory

    restart_site
    systemctl start etesync
}

function restore_local_etesync {
    if ! grep -q "etesync domain" "$COMPLETION_FILE"; then
        return
    fi
    ETESYNC_DOMAIN_NAME=$(get_completion_param "etesync domain")
    if [ ! "$ETESYNC_DOMAIN_NAME" ]; then
        return
    fi
    suspend_site "${ETESYNC_DOMAIN_NAME}"
    systemctl stop etesync

    temp_restore_dir=/root/tempetesyncdata
    etesync_dir="${ETESYNC_DATA_PATH}"

    restore_directory_from_usb $temp_restore_dir etesync
    if [ -d $temp_restore_dir ]; then
        if [ -d "$temp_restore_dir$etesync_dir" ]; then
            cp -rp "$temp_restore_dir$etesync_dir"/* "$etesync_dir"/
        else
            if [ ! -d "$etesync_dir" ]; then
                mkdir "$etesync_dir"
            fi
            cp -rp "$temp_restore_dir"/* "$etesync_dir"/
        fi
        chown -R etesync:etesync "$etesync_dir"
        rm -rf $temp_restore_dir
    fi

    temp_restore_dir=/root/tempetesync
    etesync_dir="${ETESYNC_PATH}"

    restore_directory_from_usb $temp_restore_dir etesync
    if [ -d $temp_restore_dir ]; then
        if [ -d "$temp_restore_dir$etesync_dir" ]; then
            cp -rp "$temp_restore_dir$etesync_dir"/* "$etesync_dir"/
        else
            if [ ! -d "$etesync_dir" ]; then
                mkdir "$etesync_dir"
            fi
            cp -rp "$temp_restore_dir"/* "$etesync_dir"/
        fi
        chown -R etesync:etesync "$etesync_dir"
        rm -rf $temp_restore_dir
    fi

    temp_restore_dir=/root/tempetesyncstatic
    etesync_dir="/var/www/$ETESYNC_DOMAIN_NAME/htdocs"

    restore_directory_from_usb $temp_restore_dir etesync
    if [ -d $temp_restore_dir ]; then
        if [ -d "$temp_restore_dir$etesync_dir" ]; then
            cp -rp "$temp_restore_dir$etesync_dir"/* "$etesync_dir"/
        else
            if [ ! -d "$etesync_dir" ]; then
                mkdir "$etesync_dir"
            fi
            cp -rp "$temp_restore_dir"/* "$etesync_dir"/
        fi
        chown -R www-data:www-data "$etesync_dir"
        rm -rf $temp_restore_dir
    fi

    systemctl start etesync

    restart_site
}

function backup_remote_etesync {
    echo -n ''
}

function restore_remote_etesync {
    echo -n ''
}

function remove_etesync {
    nginx_dissite "$ETESYNC_DOMAIN_NAME"
    remove_certs "$ETESYNC_DOMAIN_NAME"

    if [ -f /etc/systemd/system/etesync.service ]; then
        systemctl stop etesync
        systemctl disable etesync
        rm /etc/systemd/system/etesync.service
    fi
    userdel -r etesync
    if [ -f /usr/bin/run-etesync ]; then
        rm /usr/bin/run-etesync
    fi
    if [ -f /usr/bin/install-etesync ]; then
        rm /usr/bin/install-etesync
    fi
    if [ -f /usr/bin/upgrade-etesync ]; then
        rm /usr/bin/upgrade-etesync
    fi
    if [ -f /usr/bin/add-user-etesync ]; then
        rm /usr/bin/add-user-etesync
    fi
    if [ -f /usr/bin/remove-user-etesync ]; then
        rm /usr/bin/remove-user-etesync
    fi
    if [ -f /usr/bin/change-password-etesync ]; then
        rm /usr/bin/change-password-etesync
    fi

    if [ -d "/var/www/$ETESYNC_DOMAIN_NAME" ]; then
        rm -rf "/var/www/$ETESYNC_DOMAIN_NAME"
    fi
    if [ -f "/etc/nginx/sites-available/$ETESYNC_DOMAIN_NAME" ]; then
        rm "/etc/nginx/sites-available/$ETESYNC_DOMAIN_NAME"
    fi
    remove_onion_service etesync "${ETESYNC_ONION_PORT}"
    if grep -q "etesync" /etc/crontab; then
        sed -i "/etesync/d" /etc/crontab
    fi
    remove_app etesync
    remove_i2p_service eyesync
    remove_completion_param install_etesync
    sed -i '/etesync/d' "$COMPLETION_FILE"

    remove_ddns_domain "$ETESYNC_DOMAIN_NAME"
}

function etesync_create_ini {
    if [[ "$ONION_ONLY" == "no" ]]; then
        etesync_hostname="$ETESYNC_DOMAIN_NAME"
    else
        etesync_hostname="$ETESYNC_ONION_HOSTNAME"
    fi

    { echo '[global]';
      echo 'secret_file = secret.txt';
      echo 'debug = false';
      echo ';Set the paths where data will be stored at';
      echo "static_root = ${ETESYNC_DATA_PATH}/static";
      echo "media_root = ${ETESYNC_DATA_PATH}/media";
      echo '';
      echo ";Advanced options, only uncomment if you know what you're doing:";
      echo ";static_url = /static/";
      echo ";media_url = /user-media/";
      echo ";language_code = en-us";
      echo ";time_zone = UTC";
      echo '';
      echo '[allowed_hosts]';
      echo "allowed_host1 = ${etesync_hostname}";
      echo '';
      echo '[database]';
      echo 'engine = django.db.backends.sqlite3';
      echo 'name = db.sqlite3'; } > "${ETESYNC_PATH}/etebase-server.ini"
}

function install_etesync {
    if [ ! "$ETESYNC_DOMAIN_NAME" ]; then
        echo $'No domain name was given for etesync'
        exit 35
    fi

    increment_app_install_progress

    INSTALL_PACKAGES coreutils \
            curl file gcc git libevent-2.1-7 \
            libevent-dev libffi-dev libffi8 \
            libgnutls28-dev libjpeg62-turbo \
            libjpeg62-turbo-dev libldap-common \
            libldap2-dev libsasl2-dev \
            libsqlite3-dev libssl-dev \
            libssl3 libtool libxml2 \
            libxml2-dev libxslt1-dev libxslt1.1 \
            make python3 python3-dev \
            python3-pip python3-psycopg2 python3-django \
            python3-virtualenv sqlite3 unzip \
            zlib1g zlib1g-dev

    increment_app_install_progress

    ETESYNC_ADMIN_PASSWORD=
    if [ -f "$IMAGE_PASSWORD_FILE" ]; then
        ETESYNC_ADMIN_PASSWORD="$(printf "%s" "$(cat "$IMAGE_PASSWORD_FILE")")"
    else
        if [ ! "$ETESYNC_ADMIN_PASSWORD" ]; then
            ETESYNC_ADMIN_PASSWORD="$(create_password "${MINIMUM_PASSWORD_LENGTH}")"
        fi
    fi
    if [ ! "$ETESYNC_ADMIN_PASSWORD" ]; then
        return
    fi

    increment_app_install_progress

    if [ -d "/var/www/$ETESYNC_DOMAIN_NAME/htdocs" ]; then
        rm -rf "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
    fi
    if [ -d "${ETESYNC_PATH}" ]; then
        rm -rf "${ETESYNC_PATH}"
    fi
    mkdir "/var/www/$ETESYNC_DOMAIN_NAME"
    if [ -d /repos/etesync ]; then
        mkdir -p "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
        cp -r -p /repos/etesync/. "${ETESYNC_PATH}"
        cd "${ETESYNC_PATH}" || exit 36
        git pull
    else
        mkdir -p "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
        git_clone "$ETESYNC_REPO" "${ETESYNC_PATH}"
    fi

    increment_app_install_progress

    if [ ! -d "${ETESYNC_PATH}" ]; then
        echo $'Unable to clone etesync repo'
        exit 87
    fi

    cd "${ETESYNC_PATH}" || exit 34
    git checkout "$ETESYNC_COMMIT" -b "$ETESYNC_COMMIT"

    if [ ! -f "${ETESYNC_PATH}/requirements.txt" ]; then
        echo $'requirements.txt not found'
        exit 56
    fi

    set_completion_param "etesync commit" "$ETESYNC_COMMIT"

    chmod g+w "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"
    chown -R www-data:www-data "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"

    add_ddns_domain "$ETESYNC_DOMAIN_NAME"

    increment_app_install_progress

    ETESYNC_ONION_HOSTNAME=$(add_onion_service etesync 80 "${ETESYNC_ONION_PORT}")

    increment_app_install_progress

    sed -i "s|ALLOWED_HOSTS =.*|ALLOWED_HOSTS = [ 'localhost', '${ETESYNC_DOMAIN_NAME}', '${ETESYNC_ONION_HOSTNAME}' ]|g" "${ETESYNC_PATH}/etesync_server/settings.py"

    sed -i "s|STATIC_ROOT =.*|STATIC_ROOT = os.environ.get('DJANGO_STATICS','/var/www/$ETESYNC_DOMAIN_NAME/htdocs/')|g" "${ETESYNC_PATH}/etesync_server/settings.py"

    # place to store data
    if [ ! -d "${ETESYNC_DATA_PATH}" ]; then
        mkdir "${ETESYNC_DATA_PATH}"
    fi

    increment_app_install_progress

    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo 'pip3 install -r requirements.txt uwsgi';
      echo 'python3 manage.py migrate';
      echo 'python3 manage.py collectstatic --no-input';
      echo 'pip3 install uvicorn[standard]';
      echo 'deactivate'; } > /usr/bin/install-etesync
    chmod +x /usr/bin/install-etesync
    /bin/bash /usr/bin/install-etesync

    increment_app_install_progress

    etesync_nginx_site=/etc/nginx/sites-available/$ETESYNC_DOMAIN_NAME
    if [[ "$ONION_ONLY" == "no" ]]; then
        nginx_http_redirect "$ETESYNC_DOMAIN_NAME" "index index.html"
        { echo 'server {';
          echo '    listen 443 ssl;';
          echo '    #listen [::]:443 ssl;';
          echo "    server_name $ETESYNC_DOMAIN_NAME;";
    echo '    server_tokens off;';
          echo '';
          echo '    access_log /dev/null;';
          echo '    error_log /dev/null;';
          echo '';
          echo '    charset     utf-8;';
          echo '';
          echo '    client_max_body_size 75M;';
          echo '    location / {';
          echo "        proxy_pass  http://localhost:${ETESYNC_PORT_INTERNAL};";
          echo "        proxy_http_version 1.1;";
          echo "        proxy_set_header Upgrade \$http_upgrade;";
          echo "        proxy_set_header Connection \"upgrade\";";
          echo '';
          echo "        proxy_redirect off;";
          echo "        proxy_set_header Host \$host;";
          echo "        proxy_set_header X-Real-IP \$remote_addr;";
          echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;";
          echo "        proxy_set_header X-Forwarded-Host \$server_name;";
          echo '    }';
          echo '';
          echo '    location /static {';
          echo "        alias /var/www/$ETESYNC_DOMAIN_NAME/htdocs;";
          echo '    }';
          echo '';
          echo '    # Security'; } >> "$etesync_nginx_site"

        nginx_ssl "$ETESYNC_DOMAIN_NAME"

        nginx_security_options "$ETESYNC_DOMAIN_NAME"
        nginx_robots "$ETESYNC_DOMAIN_NAME"

        { echo '  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;';
    echo "    add_header Onion-Location http://${ETESYNC_ONION_HOSTNAME}\$request_uri;";
    echo '}'; } >> "$etesync_nginx_site"
    else
        echo -n '' > "$etesync_nginx_site"
    fi
    { echo 'server {';
      echo "    listen 127.0.0.1:$ETESYNC_ONION_PORT default_server;";
      echo "    server_name $ETESYNC_ONION_HOSTNAME;";
      echo '    server_tokens off;';
      echo '';
      echo '    access_log /dev/null;';
      echo '    error_log /dev/null;';
      echo '';
      echo '    charset     utf-8;';
      echo '';
      echo '    client_max_body_size 75M;';
      echo '    location / {';
      echo "        proxy_pass  http://localhost:${ETESYNC_PORT_INTERNAL};";
      echo "        proxy_http_version 1.1;";
      echo "        proxy_set_header Upgrade \$http_upgrade;";
      echo "        proxy_set_header Connection \"upgrade\";";
      echo '';
      echo "        proxy_redirect off;";
      echo "        proxy_set_header Host \$host;";
      echo "        proxy_set_header X-Real-IP \$remote_addr;";
      echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;";
      echo "        proxy_set_header X-Forwarded-Host \$server_name;";
      echo '    }';
      echo '';
      echo '    location /static {';
      echo "        alias /var/www/$ETESYNC_DOMAIN_NAME/htdocs;";
      echo '    }';
      echo '}'; } >> "$etesync_nginx_site"

    add_i2p_service etesync 80 $ETESYNC_I2P_PORT
    ETESYNC_I2P_HOSTNAME=$(get_i2p_domain etesync)
    if [ "$ETESYNC_I2P_HOSTNAME" ]; then
        { echo 'server {';
          echo "    listen 127.0.0.1:$ETESYNC_I2P_PORT default_server;";
          echo "    server_name $ETESYNC_I2P_HOSTNAME;";
          echo '    server_tokens off;';
          echo '';
          echo '    access_log /dev/null;';
          echo '    error_log /dev/null;';
          echo '';
          echo '    charset     utf-8;';
          echo '';
          echo '    client_max_body_size 75M;';
          echo '    location / {';
          echo "        proxy_pass  http://localhost:${ETESYNC_PORT_INTERNAL};";
          echo "        proxy_http_version 1.1;";
          echo "        proxy_set_header Upgrade \$http_upgrade;";
          echo "        proxy_set_header Connection \"upgrade\";";
          echo '';
          echo "        proxy_redirect off;";
          echo "        proxy_set_header Host \$host;";
          echo "        proxy_set_header X-Real-IP \$remote_addr;";
          echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;";
          echo "        proxy_set_header X-Forwarded-Host \$server_name;";
          echo '    }';
          echo '';
          echo '    location /static {';
          echo "        alias /var/www/$ETESYNC_DOMAIN_NAME/htdocs;";
          echo '    }';
          echo '}'; } >> "$etesync_nginx_site"
    fi

    increment_app_install_progress

    if ! grep -q "etesync:" /etc/group; then
  groupadd -r etesync
    fi
    useradd -d "$ETESYNC_PATH" -r -M -s /bin/sh -g etesync etesync

    increment_app_install_progress

    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 46";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "uvicorn etebase_server.asgi:application --port ${ETESYNC_PORT_INTERNAL} --host 0.0.0.0";
      echo 'deactivate'; } > /usr/bin/run-etesync
    chmod +x /usr/bin/run-etesync

    { echo '[Unit]';
      echo 'Description=etesync';
      echo 'After=network.target';
      echo "Documentation=$ETESYNC_REPO";
      echo '';
      echo '[Service]';
      echo 'Type=simple';
      echo 'User=etesync';
      echo 'Group=etesync';
      echo "WorkingDirectory=${ETESYNC_PATH}";
      echo "ExecStart=/usr/bin/run-etesync";
      echo 'Environment=USER=etesync';
      echo "Environment=ETESYNC_PATH=${ETESYNC_PATH}";
      echo "Environment=DATA_PATH=${ETESYNC_DATA_PATH}";
      echo "Environment=DJANGO_STATICS=/var/www/$ETESYNC_DOMAIN_NAME/htdocs";
      echo "Environment=DJANGO_PORT=${ETESYNC_PORT_INTERNAL}";
      echo 'Environment=SERVER="standalone"';
      echo "Environment=GIT_CEILING_DIRECTORIES=${ETESYNC_PATH}";
      echo 'Restart=always';
      echo 'PrivateTmp=true';
      echo 'PrivateDevices=false';
      echo 'CapabilityBoundingSet=~CAP_SYS_ADMIN';
      echo 'ProtectSystem=yes';
      echo 'ProtectHome=yes';
      echo 'ProtectClock=yes';
      echo 'ProtectHostname=yes';
      echo 'PrivateUsers=yes';
      echo 'ProtectKernelModules=yes';
      echo 'ProtectKernelTunables=yes';
      echo 'NoNewPrivileges=true';
      echo '';
      echo '[Install]';
      echo 'WantedBy=multi-user.target'; } > "/etc/systemd/system/etesync.service"
    systemctl enable etesync
    chown -R etesync:etesync "${ETESYNC_PATH}"
    systemctl start etesync

    increment_app_install_progress

    create_site_certificate "$ETESYNC_DOMAIN_NAME" 'yes'

    increment_app_install_progress

    nginx_ensite "$ETESYNC_DOMAIN_NAME"

    systemctl restart nginx

    increment_app_install_progress

    rm /usr/bin/install-etesync

    cd "${ETESYNC_PATH}" || exit 34

    chown -R www-data:www-data "/var/www/$ETESYNC_DOMAIN_NAME/htdocs"

    increment_app_install_progress

    etesync_create_ini
    mkdir "${ETESYNC_DATA_PATH}/static"
    mkdir "${ETESYNC_DATA_PATH}/media"
    chown -R etesync:etesync "$ETESYNC_DATA_PATH"
    chown -R etesync:etesync "$ETESYNC_PATH"

    etesync_temp_filename=/usr/bin/add-superuser-etesync
    { echo '#!/bin/bash';
      echo "cd ${ETESYNC_PATH} || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('$MY_USERNAME', '$MY_EMAIL_ADDRESS', '$ETESYNC_ADMIN_PASSWORD')\" | python3 manage.py shell";
      echo "\"${PROJECT_NAME}-pass\" -u \"$MY_USERNAME\" -a etesync -p \"$ETESYNC_ADMIN_PASSWORD\"";
      echo 'deactivate'; } > $etesync_temp_filename
    chmod +x $etesync_temp_filename
    if ! /bin/bash $etesync_temp_filename; then
        rm $etesync_temp_filename
        echo 'Unable to create superuser'
        exit 43
    fi
    rm $etesync_temp_filename

    increment_app_install_progress

    set_completion_param "etesync domain" "$ETESYNC_DOMAIN_NAME"

    APP_INSTALLED=1
}

# NOTE: deliberately there is no "exit 0"
