#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Make an already installed image into an image which can be redistributed
# ensuring that new keys get created
#
# License
# =======
#
# Copyright (C) 2018-2022 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='libreserver'

export TEXTDOMAIN=${PROJECT_NAME}-distro
export TEXTDOMAINDIR="/usr/share/locale"

# show the factory reset screen
local_hostname=$(grep 'host-name' /etc/avahi/avahi-daemon.conf | awk -F '=' '{print $2}').local
webadmin_install_dir="/var/www/${local_hostname}/htdocs/admin"
if [ -f "${webadmin_install_dir}/factory_resetting.html" ]; then
    cp "${webadmin_install_dir}/factory_resetting.html" "${webadmin_install_dir}/index.html"
fi

# remove basic auth
nginx_config_filename=/etc/nginx/sites-available/${local_hostname}
if [ -f "$nginx_config_filename" ]; then
    if ! grep -q "#auth_basic" "$nginx_config_filename"; then
	sed -i 's|auth_basic|#auth_basic|g' "$nginx_config_filename"
	systemctl restart nginx
    fi
fi

# remove any manual install flag
if [ -f /root/.manualinstall ]; then
    rm /root/.manualinstall
fi

# add flag to begin factory reset on next boot
if [ ! -f /root/.factoryresetdistro ]; then
    touch /root/.factoryresetdistro
fi

echo 'You can now safely create clones of this disk image'

systemctl poweroff
