#!/bin/bash
#
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# License
# =======
#
# Copyright (C) 2026 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

VARIANTS='full full-vim full-micro'

APP_CATEGORY=publishing

IN_DEFAULT_INSTALL=0
INSTALLED_ON_DEFAULT_DOMAIN=1
SHOW_ON_ABOUT=0

# whether to show the domain name in the web UI
SHOW_DOMAIN_IN_WEBADMIN=0

# whether to show https://domain or just the domain on its own on app screen
SHOW_DOMAIN_ONLY=0

# whether this app will be included in the json API for the FreedomBox android app
NOT_ON_API=0

# Whether to show on http://libreserver/home
NOT_ON_HOMEPAGE=0

# show port number within the URL on app screens
SHOW_URL_PORT=

# Whether another app is required to be installed before this one
REQUIRES_APP=

RETICULUM_DOMAIN_NAME=reticulum.local
RETICULUM_CODE=
RETICULUM_ONION_PORT=
RETICULUM_PORT_INTERNAL=

# These parameters are used by the FreedomBox mobile app and web UI
RETICULUM_SHORT_DESCRIPTION=
RETICULUM_DESCRIPTION=
RETICULUM_MOBILE_APP_URL=

# Any ports which should be added to the firewall, separated by commas
RETICULUM_FIREWALL_PORTS=""

reticulum_upgrade_filename=/usr/bin/upgrade-reticulum

reticulum_variables=(ONION_ONLY
                     RETICULUM_CODE
                     DDNS_PROVIDER
                     MY_USERNAME)

function change_default_domain_name_reticulum {
    new_default_domain_name="$1"
    # If anything references DEFAULT_DOMAIN_NAME then change it here
}

function logging_on_reticulum {
    echo -n ''
}

function logging_off_reticulum {
    echo -n ''
}

function remove_user_reticulum {
    remove_username="$1"

    "${PROJECT_NAME}-pass" -u "$remove_username" --rmapp reticulum
}

function add_user_reticulum {
    new_username="$1"
    new_user_password="$2"

    "${PROJECT_NAME}-pass" -u "$new_username" -a reticulum -p "$new_user_password"
    echo '0'
}

function install_interactive_reticulum {
    APP_INSTALLED=1
}

function change_password_reticulum {
    curr_username="$1"
    new_user_password="$2"

    "${PROJECT_NAME}-pass" -u "$curr_username" -a reticulum -p "$new_user_password"
}

function reconfigure_reticulum {
    # This is used if you need to switch identity. Dump old keys and generate new ones
    echo -n ''
}

function configure_interactive_reticulum {
    W=(1 $"Add a peer"
       2 $"Remove a peer")

    while true
    do
        # shellcheck disable=SC2068
        selection=$(dialog --backtitle $"LibreServer Administrator Control Panel" --title $"reticulum" --menu $"Choose an operation, or ESC for main menu:" 14 70 3 "${W[@]}" 3>&2 2>&1 1>&3)

        if [ ! "$selection" ]; then
           break
        fi
        case $selection in
            1) # Add a peer
               ;;
            2) # remove a peer
               ;;
        esac
    done
}

function upgrade_distro_reticulum {
    target_distro="$1"
    # include anything here needed to upgrade to the target distro
}

function upgrade_reticulum {
    /bin/bash ${reticulum_upgrade_filename}
}

function backup_local_reticulum {
    source_directory=/etc/reticulum

    systemctl stop reticulum
    dest_directory=reticulum
    backup_directory_to_usb "$source_directory" $dest_directory
    systemctl start reticulum
}

function restore_local_reticulum {
    systemctl stop reticulum

    temp_restore_dir=/root/tempreticulum
    reticulum_dir=/etc/reticulum

    restore_directory_from_usb $temp_restore_dir reticulum
    if [ -d $temp_restore_dir ]; then
        if [ -d "$temp_restore_dir$reticulum_dir" ]; then
            cp -rp "$temp_restore_dir$reticulum_dir"/* "$reticulum_dir"/
        else
            if [ ! -d "$reticulum_dir" ]; then
                mkdir "$reticulum_dir"
            fi
            cp -rp "$temp_restore_dir"/* "$reticulum_dir"/
        fi
        chown -R reticulum:reticulum "$reticulum_dir"
        rm -rf $temp_restore_dir
        restoring_reticulum=1
    fi
    systemctl start reticulum

    restoring_reticulum=
}

function backup_remote_reticulum {
    echo -n ''
}

function restore_remote_reticulum {
    echo -n ''
}

function remove_reticulum {
    if [ -f /etc/systemd/system/reticulum.service ]; then
        systemctl stop reticulum
        systemctl disable reticulum
        rm /etc/systemd/system/reticulum.service
    fi
    userdel -r reticulum

    if [ -f ${reticulum_upgrade_filename} ]; then
        rm ${reticulum_upgrade_filename}
    fi

    if [ -d "/var/www/$RETICULUM_DOMAIN_NAME" ]; then
        rm -rf "/var/www/$RETICULUM_DOMAIN_NAME"
    fi
    remove_app reticulum
    remove_completion_param install_reticulum
    sed -i '/reticulum/d' "$COMPLETION_FILE"
}

function firewall_reticulum {
    reticulum_dummy_variable=1
}

function create_reticulum_config {
    reticulum_config_filename="$1"
    { echo '[reticulum]';
      echo 'enable_transport = True';
      echo 'share_instance = Yes';
      echo 'instance_name = default';
      echo '# shared_instance_port = 37428';
      echo '# instance_control_port = 37429';
      echo '# shared_instance_type = tcp';
      echo '# discover_interfaces = No';
      echo '# panic_on_interface_error = No';
      echo '# blackhole_sources = 521c87a83afb8f29e4455e77930b973b';
      echo '[logging]';
      echo '  loglevel = 0';
      echo '[interfaces]';
      echo '  [[Default Interface]]';
      echo '    type = AutoInterface';
      echo '    enabled = Yes';
      echo '';
      echo '  [[I2P]]';
      echo '    type = I2PInterface';
      echo '    enabled = yes';
      echo '    connectable = yes';
      echo '';
      echo '  [[RNS Testnet BetweenTheBorders]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = reticulum.betweentheborders.com';
      echo '    target_port = 4242';
      echo '';
      echo '  [[dismails TCP Interface]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = rns.dismail.de';
      echo '    target_port = 7822';
      echo '';
      echo '  [[Beleth RNS Hub]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = rns.beleth.net';
      echo '    target_port = 4242';
      echo '';
      echo '  [[Bern IPv4]]';
      echo '    type = BackboneInterface';
      echo '    enabled = yes';
      echo '    remote = 45.59.114.96';
      echo '    target_port = 7822';
      echo '    transport_identity = 521c87a83afb8f29e4455e77930b973b';
      echo '';
      echo '  [[noDNS1]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = 202.61.243.41';
      echo '    target_port = 4965';
      echo '';
      echo '  [[noDNS2]]';
      echo '    type = BackboneInterface';
      echo '    enabled = yes';
      echo '    remote = 193.26.158.230';
      echo '    target_port = 4965';
      echo '    transport_identity = 0c5d8effbd2f288f6ec03ac5e3f24fde';
      echo '';
      echo '  [[reticulum.n7ekb.net]]';
      echo '    type = TCPClientInterface';
      echo '    mode = gateway';
      echo '    enabled = yes';
      echo '    target_host = reticulum.n7ekb.net';
      echo '    target_port = 48086';
      echo '';
      echo '  [[rmap world]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = rmap.world';
      echo '    target_port = 4242';
      echo '';
      echo '  [[RNS bnZ-NODE01]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = 91.207.113.250';
      echo '    target_port = 4242';
      echo '';
      echo '  [[RNS bnZ-RET01]]';
      echo '    type = TCPClientInterface';
      echo '    enabled = yes';
      echo '    target_host = 213.89.12.80';
      echo '    target_port = 4242';
      echo '';
      echo '  [[I2P bnZ-NODE01]]';
      echo '    type = I2PInterface';
      echo '    enabled = yes';
      echo '    peers = onsilnrvpyxipyxyc32lnvzvmxiivkppi6a2hifhl22owomlug7a.b32.i2p';
      echo '';
      echo '  [[I2P bnZ-RET01]]';
      echo '    type = I2PInterface';
      echo '    enabled = yes';
      echo '    peers = lzesnlrl3dlpxuunb4cj2hdw2eil4x5sp4d2dkrcbl2nvyqqxfnq.b32.i2p';
      echo '';
      echo '  [[FireZen-I2P]]';
      echo '    type = I2PInterface';
      echo '    enabled = yes';
      echo '    peers = ap6b2z5lltdlqq7osdj2o3qgchjdborbnezh53p3vgrcggsymfta.b32.i2p'; } > "${reticulum_config_filename}"
}

function install_reticulum {
    increment_app_install_progress

    if [ -d "/var/www/$RETICULUM_DOMAIN_NAME/htdocs" ]; then
        rm -rf "/var/www/$RETICULUM_DOMAIN_NAME/htdocs"
    fi
    mkdir -p "/var/www/$RETICULUM_DOMAIN_NAME/htdocs"
    mkdir "/etc/reticulum"
    cd "/etc/reticulum" || exit 34

    chmod g+w "/var/www/$RETICULUM_DOMAIN_NAME/htdocs"
    chown -R www-data:www-data "/var/www/$RETICULUM_DOMAIN_NAME/htdocs"

    increment_app_install_progress

    INSTALL_PACKAGES python3-pip python3-virtualenv

    increment_app_install_progress

    { echo '#!/bin/bash';
      echo "cd /etc/reticulum || exit 1";
      echo 'virtualenv -p python3 .venv';
      echo 'source .venv/bin/activate';
      echo "pip3 install -U rns";
      echo 'deactivate'; } > ${reticulum_upgrade_filename}
    chmod +x ${reticulum_upgrade_filename}
    /bin/bash ${reticulum_upgrade_filename}

    increment_app_install_progress

    adduser --system --home="/etc/reticulum" --group reticulum

    create_reticulum_config /etc/reticulum/config

    increment_app_install_progress

    { echo '[Unit]';
      echo 'Description=reticulum';
      echo 'After=network.target';
      echo "Documentation=https://reticulum.miraheze.org/wiki";
      echo '';
      echo '[Service]';
      echo 'Type=simple';
      echo 'User=reticulum';
      echo 'Group=reticulum';
      echo 'WorkingDirectory=/etc/reticulum';
      echo "ExecStart=/etc/reticulum/.venv/bin/python3 .venv/bin/rnsd -v -s";
      echo 'Environment=USER=reticulum';
      echo 'Restart=always';
      echo 'ProtectHome=true';
      echo 'ProtectKernelTunables=true';
      echo 'ProtectKernelModules=true';
      echo 'ProtectControlGroups=true';
      echo 'ProtectKernelLogs=true';
      echo 'ProtectHostname=true';
      echo 'ProtectClock=true';
      echo 'ProtectProc=invisible';
      echo 'ProcSubset=pid';
      echo 'PrivateTmp=true';
      echo 'PrivateUsers=true';
      echo 'PrivateDevices=true';
      echo 'PrivateIPC=true';
      echo 'MemoryDenyWriteExecute=true';
      echo 'NoNewPrivileges=true';
      echo 'LockPersonality=true';
      echo 'RestrictRealtime=true';
      echo 'RestrictSUIDSGID=true';
      echo 'RestrictAddressFamilies=AF_INET';
      echo 'RestrictNamespaces=true';
      echo 'SystemCallArchitectures=native';
      echo '';
      echo '[Install]';
      echo 'WantedBy=multi-user.target'; } > "/etc/systemd/system/reticulum.service"
    systemctl enable reticulum
    chown -R reticulum:reticulum "/etc/reticulum"
    systemctl start reticulum

    increment_app_install_progress

    "${PROJECT_NAME}-pass" -u "$MY_USERNAME" -a reticulum -p "$RETICULUM_ADMIN_PASSWORD"
    firewall_reticulum

    increment_app_install_progress

    APP_INSTALLED=1
}

# NOTE: deliberately there is no "exit 0"
