#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Functions for MassMesh DNS resolution
#
# License
# =======
#
# Copyright © 2019-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

MASSMESH_NODES="http://map.meshte.ch/api/routers_by_location?bbox=-74.8883056640625%2C41.18278832811288%2C-66.9781494140625%2C43.28920196020127"

function update_mesh_nodes_mass {
    if [ ! -d /etc/massmesh ]; then
        return
    fi

    { echo 'import json';
      echo 'import requests';
      echo '';
      echo "file = open(\"network_map_markers.txt\",\"w\")";
      echo '';
      echo "data = requests.get(\"$MASSMESH_NODES\").json()['rows']";
      echo '';
      echo 'for elem in data:';
      # shellcheck disable=SC2028
      echo "    file.write(elem['id'] + \";\" + str(elem['geometry']['coordinates'][0]) + \";\" + str(elem['geometry']['coordinates'][1]) + '\n')";
      echo '';
      echo 'file.close()'; } > parse_map.py

    python3 parse_map.py
    rm parse_map.py
    if [ -f network_map_markers.txt ]; then
        create_kml_from_markers network_map_markers.txt network_map_markers.kml
        chown www-data:www-data network_map_markers.kml
        chown www-data:www-data network_map_markers.txt
        echo $"$(wc -l network_map_markers.txt | awk -F ' ' '{print $1}') installed massmesh nodes"
    else
        echo $"0 installed massmesh nodes"
    fi
}

function setup_mesh_mass {
    if [ -d /etc/massmesh ]; then
        return
    fi

    mkdir /etc/massmesh

    set_map_location '-71.0597700' '42.3584300'
}

function remove_mesh_mass {
    rm -rf /etc/massmesh
}

# NOTE: deliberately no exit 0
