#!/usr/bin/python3
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Removes html from emails, turning them into plain text only.
# This mitigates a lot of common security problems.
#
# License
# =======
#
# Copyright (C) 2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import html2text
import email
from email.parser import Parser
from email.parser import HeaderParser
import urllib.parse as ul
import os
import sys

# read the email from stdin
emailtext = ''
for l in sys.stdin:
    emailtext += l

# don't convert if there is no html
if 'text/html' not in emailtext and \
   '<html' not in emailtext:
    print(emailtext)
    sys.exit()

# get the headers
parser = HeaderParser()
h = parser.parsestr(emailtext)

fromAddresses = None
for key,value in h.items():
    if key == 'From':
        fromAddresses = value.strip()
        break

# allow some html email senders through
if fromAddresses:
    exceptionsFilename = '/root/allow_html_emails.txt'
    if os.path.isfile(exceptionsFilename):
        with open(exceptionsFilename, "r") as f:
            allowedAddresses = f.readlines()
            for adr in allowedAddresses:
                adr = adr.replace('\n', '').replace('\r', '')
                if adr in fromAddresses:
                    print(emailtext)
                    sys.exit()

for key,value in h.items():
    if key.lower() == 'content-type':
        value = 'text/plain'
    print(key + ': ' + value)
print('')

# get the email body
msg = email.message_from_string(emailtext)
isValid = False
for part in msg.walk():
    # multipart/* are just containers
    if part.get_content_maintype() == 'multipart':
        continue
    isValid = True
    print(html2text.html2text(part.get_payload(decode=True).decode('utf8')))

if not isValid:
    print('___INVALID___')
