#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# TURN server functions
# NOTE: the turnserver package is deprecated in Debian 10 
#
# License
# =======
#
# Copyright (C) 2016-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TURN_PORT=3478
TURN_TLS_PORT=5349

function install_turn {
    # since this depends on udp, it's not going to work through Tor
    if [[ "$ONION_ONLY" != 'no' ]]; then
	return
    fi

    domain=$DEFAULT_DOMAIN_NAME

    turn_cert="/etc/letsencrypt/live/${domain}/fullchain.pem"
    if [ ! -f "$turn_cert" ]; then
	return
    fi
    turn_pkey="/etc/letsencrypt/live/${domain}/privkey.pem"
    if [ ! -f "$turn_pkey" ]; then
	return
    fi

    INSTALL_PACKAGES coturn
    firewall_add turn ${TURN_PORT}
    firewall_add turntls ${TURN_TLS_PORT}
    firewall_add_range turnrange 49152 65535 udp
    
    curr_ipv4=$(get_external_ipv4_address)
    { echo "listening-port=${TURN_PORT}";
      echo "tls-listening-port=${TURN_TLS_PORT}";
      echo '';
      echo '# Your external IP, needed for some connections';
      echo "relay-ip=${curr_ipv4}";
      echo "external-ip=${curr_ipv4}/$(get_local_ipv4_address)";
      echo '';
      echo "realm=${domain}";
      echo '';
      echo 'min-port=49152';
      echo 'max-port=65535';
      echo '';
      echo 'use-auth-secret';
      echo "static-auth-secret=$(create_random_string 30)$(create_random_string 30)";
      echo '';
      echo "#Paths to certificates";
      echo "cert=${turn_cert}";
      echo "pkey=${turn_pkey}";
      echo 'dh2066';
      echo ''
      echo '# Log to syslog'
      echo '#syslog';
      echo '';
      echo '# disallow server fingerprinting';
      echo 'prod';
      echo '# disable command-line access';
      echo 'no-cli';
      echo '#no-stun';
      echo 'total-quota=100';
      echo 'no-multicast-peers'; } > /etc/turnserver.conf
    
    sed -i "s|#TURNSERVER_ENABLED.*|TURNSERVER_ENABLED=1|g" /etc/default/coturn
    sed -i "s|TURNSERVER_ENABLED.*|TURNSERVER_ENABLED=1|g" /etc/default/coturn

    systemctl restart coturn

    { echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->';
      echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">';
      echo '<service-group>';
      echo '  <name replace-wildcards="yes">%h TURN</name>';
      echo '  <service>';
      echo '    <type>_turn._tcp</type>';
      echo "    <port>$TURN_PORT</port>";
      echo '  </service>';
      echo '  <service>';
      echo '    <type>_turn._udp</type>';
      echo "    <port>$TURN_PORT</port>";
      echo '  </service>';
      echo '  <service>';
      echo '    <type>_turns._tcp</type>';
      echo "    <port>$TURN_TLS_PORT</port>";
      echo '  </service>';
      echo '  <service>';
      echo '    <type>_turns._udp</type>';
      echo "    <port>$TURN_TLS_PORT</port>";
      echo '  </service>';
      echo '</service-group>'; } > /etc/avahi/services/turn.service
    systemctl restart avahi-daemon
}

function remove_turn {
    if [[ "$ONION_ONLY" != 'no' ]]; then
	return
    fi
    firewall_remove ${TURN_TLS_PORT}
    firewall_remove ${TURN_PORT}
    firewall_remove_range 49152 65535 udp
    systemctl stop coturn
    $REMOVE_PACKAGES coturn
    rm /etc/avahi/services/turn.service
    systemctl restart avahi-daemon
}

function change_default_domain_name_turn {
    new_default_domain_name="$1"
    sed -i "s|realm=.*|realm=${new_default_domain_name}|g" /etc/turnserver.conf
    systemctl restart coturn
}

# NOTE: deliberately no exit 0
