#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Avahi functions
#
# License
# =======
#
# Copyright (C) 2014-2022 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function create_avahi_service {
    # see https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
    service_type=$1
    service_name=$2
    service_protocol=$3
    service_port=$4
    service_description="$5"

    if [ ! -d /etc/avahi ]; then
        echo $'create_avahi_service: avahi was not installed'
        exit 52
    fi

    { echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->';
      echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">';
      echo '<service-group>';
      echo "  <name replace-wildcards=\"yes\">%h ${service_name}</name>";
      echo '  <service>';
      echo "    <type>_${service_name}._${service_protocol}</type>";
      echo "    <port>${service_port}</port>"; }  > "/etc/avahi/services/${service_type}.service"

    if [ "$service_description" ]; then
        echo "    <txt-record>$service_description</txt-record>" >> "/etc/avahi/services/${service_type}.service"
    fi

    { echo '  </service>';
      echo '</service-group>'; } >> "/etc/avahi/services/${service_type}.service"
}

function mesh_avahi {
    # shellcheck disable=SC2154,SC2086
    chroot "$rootdir" INSTALL_PACKAGES avahi-utils avahi-dnsconfd

    decarray=( 1 2 3 4 5 6 7 8 9 0 )
    PEER_ID=${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}
    sed -i "s|#host-name=.*|host-name=P$PEER_ID|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|host-name=.*|host-name=P$PEER_ID|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i 's|#domain-name=.*|domain-name=local|g' "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i 's|domain-name=.*|domain-name=local|g' "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|use-ipv4=.*|use-ipv4=no|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|use-ipv6=.*|use-ipv6=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#enable-dbus=.*|enable-dbus=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|enable-dbus=.*|enable-dbus=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"

    # Note: wlan interfaces must be allowed within avahi, otherwise the
    #       *.local address will not resolve

    sed -i "s|#allow-interfaces|allow-interfaces|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|allow-interfaces=.*|allow-interfaces=wlan0, wlan1, wlan2, wlan3, wlan4, wlan5, eth0, eth1|g" "$rootdir/etc/avahi/avahi-daemon.conf"

    #sed -i "s|#deny-interfaces=.*|deny-interfaces=eth0, eth1, eth2, eth3, eth4, eth5|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    #sed -i "s|deny-interfaces=.*|deny-interfaces=eth0, eth1, eth2, eth3, eth4, eth5|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#disallow-other-stacks=.*|disallow-other-stacks=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|disallow-other-stacks=.*|disallow-other-stacks=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#publish_addresses=.*|publish_addresses=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|publish_addresses=.*|publish_addresses=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#publish-hinfo=.*|publish-hinfo=no|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|publish-hinfo=.*|publish-hinfo=no|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#publish-workstation=.*|publish-workstation=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|publish-workstation=.*|publish-workstation=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#publish-domain=.*|publish-domain=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|publish-domain=.*|publish-domain=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#publish-a-on-ipv6=.*|publish-a-on-ipv6=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|publish-a-on-ipv6=.*|publish-a-on-ipv6=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|#allow-point-to-point=.*|allow-point-to-point=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"
    sed -i "s|allow-point-to-point=.*|allow-point-to-point=yes|g" "$rootdir/etc/avahi/avahi-daemon.conf"

    if [ ! -d "$rootdir/etc/avahi/services" ]; then
        mkdir -p "$rootdir/etc/avahi/services"
    fi

    # remove an avahi service which isn't used
    if [ -f "$rootdir/etc/avahi/services/udisks.service" ]; then
        rm "$rootdir/etc/avahi/services/udisks.service"
    fi

    # Add a mesh routing protocol service
    { echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->';
      echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">';
      echo '<service-group>';
      echo '  <name replace-wildcards="yes">%h routing</name>';
      echo '  <service>';
      echo '    <type>_bmx6._tcp</type>';
      echo '  </service>';
      echo '</service-group>'; } > "$rootdir/etc/avahi/services/routing.service"

    # keep the daemon running
    WATCHDOG_SCRIPT_NAME="keepon"
    { echo '';
      echo '# keep avahi daemon running';
      echo "AVAHI_RUNNING=\$(systemctl is-active avahi-daemon >/dev/null 2>&1 && echo Running)";
      echo "if [ ! \$AVAHI_RUNNING ]; then";
      echo '  systemctl start avahi-daemon';
      echo "  echo -n \$CURRENT_DATE >> \$LOGFILE";
      echo "  echo \" Avahi daemon restarted\" >> \$LOGFILE";
      echo 'fi'; } >> "$rootdir/usr/bin/$WATCHDOG_SCRIPT_NAME"
    chmod +x "$rootdir/usr/bin/$WATCHDOG_SCRIPT_NAME"
}

function keep_avahi_running {
    WATCHDOG_SCRIPT_NAME="keepon"

    if grep -q "avahi daemon" "/usr/bin/$WATCHDOG_SCRIPT_NAME"; then
        return
    fi

    { echo '';
      echo '# keep avahi daemon running';
      echo "AVAHI_RUNNING=\$(systemctl is-active avahi-daemon >/dev/null 2>&1 && echo Running)";
      echo "if [ ! \$AVAHI_RUNNING ]; then";
      echo '  systemctl start avahi-daemon';
      echo "  echo -n \$CURRENT_DATE >> \$LOGFILE";
      echo "  echo \" Avahi daemon restarted\" >> \$LOGFILE";
      echo 'fi';
      echo '# End of avahi'; } >> "/usr/bin/$WATCHDOG_SCRIPT_NAME"
    chmod +x "/usr/bin/$WATCHDOG_SCRIPT_NAME"

    # This is a bit of a hack to ensure that avahi services get broadcast
    # Without this some other systems may not be able to see the server
    { echo '#!/bin/bash';
      echo 'systemctl restart avahi-daemon'; } > /usr/bin/restartavahi
    chmod +x /usr/bin/restartavahi

    cron_add_mins 10 /usr/bin/restartavahi
}

function install_avahi {
    if [ "$INSTALLING_MESH" ]; then
        mesh_avahi
        return
    fi
    if [[ $(is_completed "${FUNCNAME[0]}") == "1" ]]; then
        return
    fi
    # only enable avahi if we're doing mesh networking
    if [[ $ENABLE_BATMAN != "yes" ]]; then
        return
    fi

    if ! "${PROJECT_NAME}-mesh-install" -f avahi; then
        echo $'Failed to install avahi'
        exit 68
    fi

    if [ "$DEFAULT_DOMAIN_NAME" ]; then
        sed -i "s|#host-name=.*|host-name=$LOCAL_NAME|g" /etc/avahi/avahi-daemon.conf
        sed -i "s|host-name=.*|host-name=$LOCAL_NAME|g" /etc/avahi/avahi-daemon.conf
    else
        decarray=( 1 2 3 4 5 6 7 8 9 0 )
        PEER_ID=${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}${decarray[$RANDOM%10]}
        sed -i "s|#host-name=.*|host-name=P$PEER_ID|g" /etc/avahi/avahi-daemon.conf
        sed -i "s|host-name=.*|host-name=P$PEER_ID|g" /etc/avahi/avahi-daemon.conf
    fi
    sed -i 's|#domain-name=.*|domain-name=local|g' /etc/avahi/avahi-daemon.conf
    sed -i 's|domain-name=.*|domain-name=local|g' /etc/avahi/avahi-daemon.conf

    mark_completed "${FUNCNAME[0]}"
}

function configure_firewall_for_avahi {
    if [[ $(is_completed "${FUNCNAME[0]}") == "1" ]]; then
        return
    fi

    firewall_add avahi1 548
    firewall_add_range avahi2 5353 5354

    function_check save_firewall_settings
    save_firewall_settings
    mark_completed "${FUNCNAME[0]}"
}

# NOTE: deliberately there is no "exit 0"
