#!/bin/bash
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# rust functions
#
# License
# =======
#
# Copyright (C) 2014-2023 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function install_rust {
    new_rust_version="$1"

    RUSTUP_HOME=/rust
    CARGO_HOME=/cargo
    if [ ! -d /rust ]; then
	mkdir /rust
    fi
    if [ ! -d /cargo ]; then
	mkdir /cargo
    fi
    if [ ! -d "${INSTALL_DIR}/rust" ]; then
	mkdir "${INSTALL_DIR}/rust"
    fi
    PATH=/cargo/bin:/rust/bin:$PATH

    cd "${INSTALL_DIR}" || return
    curl -sSfL 'https://sh.rustup.rs' -o rustup-init.sh
    chmod +x rustup-init.sh
    TMPDIR="${INSTALL_DIR}/rust" ./rustup-init.sh -y --no-modify-path --profile minimal --default-toolchain=${new_rust_version}
    rm rustup-init.sh
    TMPDIR=/tmp
}

# NOTE: deliberately no exit 0
