#!/bin/bash
#  _    _ _            ___
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|
#
# login functions
#
# License
# =======
#
# Copyright (C) 2014-2023 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function change_login_message {
    if [[ $(is_completed "${FUNCNAME[0]}") == "1" ]]; then
        return
    fi

    # remove automatic motd creator if it exists
    if [ -f /etc/init.d/motd ]; then
        rm -f /etc/init.d/motd
    fi

    { echo '  _    _ _            ___                      ';
      echo ' | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ ';
      echo " | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|";
      echo ' |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  ';
      echo ''; } > /etc/motd

    mark_completed "${FUNCNAME[0]}"
}

# NOTE: deliberately no exit 0
