#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Filesystem encryption, etc
#
# License
# =======
#
# Copyright (C) 2014-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function defrag_filesystem {
    fs_type=$(stat -f /)

    if [[ "$fs_type" != *"btrfs"* && "$fs_type" != *"ext4"* ]]; then
        return
    fi

    echo $'Defragmenting root directory'

    if [[ "$fs_type" == *"btrfs"* ]]; then
        btrfs filesystem defragment -r -clzo /
    fi

    if [[ "$fs_type" == *"ext4"* ]]; then
        e4defrag /
    fi

    echo $'Defragmentation completed'
}

function optimise_filesystem {
    if grep -q "btrfs" /etc/fstab; then
        if ! grep -q "btrfs defaults,subvol=@,compress=lzo,ssd" /etc/fstab; then
            sed -i 's|btrfs subvol=@|btrfs defaults,subvol=@,compress=lzo,ssd|g' /etc/fstab
        fi
    fi
}

# NOTE: deliberately no exit 0
