#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# freeciv game
#
# NOTE: Don't use the admin password in dm_file because this
# will likely be transmitted in the clear over $FREECIV_PORT
#
# License
# =======
#
# Copyright (C) 2019-2021 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

VARIANTS='full full-vim games'

APP_CATEGORY=games

IN_DEFAULT_INSTALL=0
SHOW_ON_ABOUT=1
SHOW_DOMAIN_ONLY=1
SHOW_APP_PORT=5863
NOT_ON_HOMEPAGE=1
REQUIRES_APP=

FREECIV_DOMAIN_NAME=
FREECIV_CODE=

FREECIV_PORT=5863
FREECIV_DIR=/var/games/freeciv

FREECIV_SHORT_DESCRIPTION=$'Freeciv Server'
FREECIV_DESCRIPTION=$'Freeciv Server'
FREECIV_MOBILE_APP_URL=""

freeciv_variables=(ONION_ONLY
		   SYSTEM_TYPE
                   MY_USERNAME)

function upgrade_distro_freeciv {
    target_distro="$1"

    if [[ "$target_distro" == 'bullseye' ]]; then
        echo -n ''
    fi
}

function logging_on_freeciv {
    if [ ! -f /etc/systemd/system/freeciv-server.service ]; then
	return
    fi
    if ! grep -q "l $FREECIV_DIR/logfile" /etc/systemd/system/freeciv-server.service; then
	sed -i "s|ExecStart=.*|ExecStart=/usr/games/freeciv-server -q 60 -p ${FREECIV_PORT} -d 2 -l $FREECIV_DIR/logfile -s ${FREECIV_DIR}/saves|g" /etc/systemd/system/freeciv-server.service
	systemctl daemon-reload
	systemctl restart freeciv-server
    fi
}

function logging_off_freeciv {
    if [ ! -f /etc/systemd/system/freeciv-server.service ]; then
	return
    fi
    if ! grep -q "l /dev/null" /etc/systemd/system/freeciv-server.service; then
	sed -i "s|ExecStart=.*|ExecStart=/usr/games/freeciv-server -q 60 -p ${FREECIV_PORT} -d 2 -l /dev/null -s ${FREECIV_DIR}/saves|g" /etc/systemd/system/freeciv-server.service
	systemctl daemon-reload
	systemctl restart freeciv-server
    fi
}

function install_interactive_freeciv {
    echo -n ''
    APP_INSTALLED=1
}

function reconfigure_freeciv {
    echo -n ''
}

function upgrade_freeciv {
    echo -n ''
}

function backup_local_freeciv {
    source_directory=$FREECIV_DIR
    if [ -d $source_directory ]; then
        dest_directory=freeciv
        function_check backup_directory_to_usb
        backup_directory_to_usb $source_directory $dest_directory
    fi
}

function restore_local_freeciv {
    if [ -d $FREECIV_DIR ]; then
        if [ -d "$USB_MOUNT_FREECIV/backup/freeciv" ]; then
            echo $"Restoring FREECIV"
            temp_restore_dir=/root/tempfreeciv
            function_check restore_directory_from_usb
            restore_directory_from_usb $temp_restore_dir freeciv
            if [ -d $temp_restore_dir$FREECIV_DIR ]; then
                cp -r $temp_restore_dir$FREECIV_DIR/* $FREECIV_DIR/
            else
                cp -r $temp_restore_dir/* $FREECIV_DIR/
            fi
	    chown -R freeciv:freeciv "$FREECIV_DIR"	    
            # shellcheck disable=SC2181
            if [ ! "$?" = "0" ]; then
                rm -rf $temp_restore_dir
                function_check set_user_permissions
                set_user_permissions
                function_check backup_unmount_drive
                backup_unmount_drive
                exit 99
            fi
            rm -rf $temp_restore_dir
        fi
    fi
}

function backup_remote_freeciv {
    echo -n ''
}

function restore_remote_freeciv {
    echo -n ''
}

function remove_freeciv {
    systemctl stop freeciv-server
    systemctl disable freeciv-server
    rm /etc/systemd/system/freeciv-server.service

    remove_onion_service freeciv ${FREECIV_PORT}

    $REMOVE_PACKAGES_PURGE freeciv*

    remove_app freeciv
    remove_completion_param install_freeciv
    sed -i '/freeciv/d' "$COMPLETION_FILE"

    if [ -d /var/www/freeciv ]; then
        rm -rf /var/www/freeciv
    fi
    if [ -d $FREECIV_DIR ]; then
        rm -rf $FREECIV_DIR
    fi
    firewall_remove ${FREECIV_PORT}
    groupdel -f freeciv
    userdel -r freeciv
}

function install_freeciv {
    if ! grep -q "freeciv:" /etc/group; then
	groupadd freeciv
    fi
    useradd -c "Freeciv Server" -d "$FREECIV_DIR" -m -r -g freeciv freeciv

    increment_app_install_progress

    if [ ! -d "$FREECIV_DIR" ]; then
	mkdir "$FREECIV_DIR"
    fi
    if [ ! -d "$FREECIV_DIR/saves" ]; then
	mkdir "$FREECIV_DIR/saves"
    fi
   
    increment_app_install_progress

    if [ -d /var/www/freeciv ]; then
        rm -rf /var/www/freeciv
    fi
    mkdir -p /var/www/freeciv/htdocs

    increment_app_install_progress

    chown -R www-data:www-data /var/www/freeciv/htdocs

    increment_app_install_progress

    INSTALL_PACKAGES freeciv-server    

    if [ ! -f /usr/games/freeciv-server ]; then
        echo $'Unable to install /usr/games/freeciv-server'
        exit 32
    fi    

    increment_app_install_progress

    FREECIV_ONION_HOSTNAME=$(add_onion_service freeciv ${FREECIV_PORT} ${FREECIV_PORT})
    
    increment_app_install_progress
    
    firewall_add freeciv ${FREECIV_PORT}

    chown -R freeciv:freeciv "$FREECIV_DIR"

    { echo '[Unit]';
      echo 'Description=Freeciv Server';
      echo 'After=network.target';
      echo '';
      echo '[Service]';
      echo 'Type=simple';
      echo 'User=freeciv';
      echo 'Group=freeciv';
      echo "WorkingDirectory=${FREECIV_DIR}";
      echo "ExecStart=/usr/games/freeciv-server -q 60 -p ${FREECIV_PORT} -d 2 -l /dev/null -s ${FREECIV_DIR}/saves";
      echo 'Restart=on-failure';
      echo 'RestartSec=10';
      echo 'PrivateTmp=true';
      echo 'PrivateDevices=false';
      echo 'NoNewPrivileges=true';
      echo 'CapabilityBoundingSet=~CAP_SYS_ADMIN';
      echo 'CPUQuota=30%';
      echo '';
      echo '[Install]';
      echo 'WantedBy=multi-user.target'; } > /etc/systemd/system/freeciv-server.service
    systemctl enable freeciv-server
    increment_app_install_progress
    systemctl daemon-reload
    increment_app_install_progress
    systemctl restart freeciv-server
    increment_app_install_progress

    APP_INSTALLED=1
}

# NOTE: deliberately no exit 0
