#!/bin/bash
#  _    _ _            ___                      
# | |  (_) |__ _ _ ___/ __| ___ _ ___ _____ _ _ 
# | |__| | '_ \ '_/ -_)__ \/ -_) '_\ V / -_) '_|
# |____|_|_.__/_| \___|___/\___|_|  \_/\___|_|  
#
# Functions for Freifunk bremen mesh DNS resolution
#
# VPN routes: https://github.com/FreifunkBremen/gatemon/blob/master/gatemon-setup.nonroot.sh
#
# License
# =======
#
# Copyright © 2019-2022 Bob Mottram <bob@libreserver.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FFBREMEN_REPO="https://github.com/FreifunkBremen/ffhb-dns"

function setup_mesh_ffbremen {
    if grep -q 'ffbremen' /etc/crontab; then
        if [ -d /etc/ffbremen ]; then
            if [ -d /etc/pihole ]; then
                systemctl stop dnsmasq
                systemctl disable dnsmasq
            fi
            cd /etc/ffbremen || return
            git stash
            git pull
            return
        fi
    fi

    if [ -d /etc/pihole ]; then
        systemctl stop dnsmasq
        systemctl disable dnsmasq
	INSTALL_PACKAGES knot-resolver knot
    fi

    git clone $FFBREMEN_REPO /etc/ffbremen
    cd /etc/ffbremen || exit 62

    { echo '#!/bin/bash';
      echo 'cd /etc/ffbremen || exit 0';
      echo 'git stash';
      echo 'git pull';
      echo 'cp /etc/ffbremen/*.zone /var/lib/knot/zones';
      echo 'systemctl restart knot';
      echo 'systemctl stop kresd.service';
      echo 'sleep 2';
      echo 'systemctl start kresd.socket';
      echo 'systemctl restart system-kresd.slice'; } > /etc/ffbremen/deploy.sh
    chmod +x /etc/ffbremen/deploy.sh

    /bin/bash /etc/ffbremen/deploy.sh
    
    if ! grep -q 'ffbremen' /etc/crontab; then
        echo "*/30 * * * *   root    cd /etc/ffbremen && /etc/ffbremen/deploy.sh 2>&1 > /dev/null" >> /etc/crontab
    fi
}

function remove_mesh_ffbremen {
    if grep -q 'ffbremen' /etc/crontab; then
        sed -i '/ffbremen/d' /etc/crontab
    fi

    # remove existing config
    rm -rf /var/lib/knot/zones/*

    # restore previous config
    cp /etc/knot-resolver/kresd_prev.conf /etc/knot-resolver/kresd.conf
    cp /etc/knot/knot_prev.conf /etc/knot/knot.conf
    chown knot:knot /etc/knot/knot.conf

    rm -rf /etc/ffbremen

    if [ -d /etc/pihole ]; then
        $REMOVE_PACKAGES knot-resolver knot
        systemctl enable dnsmasq
        systemctl start dnsmasq
    else
        # restart knot daemons
        systemctl restart knot
        systemctl restart kresd.socket
        systemctl restart system-kresd.slice
    fi
}

# NOTE: deliberately no exit 0
